# -*- coding: utf-8 -*-
"""Bipartite Network + Island Method + Visuals

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tx7mz5_mIl_Hxgly6DQOOA2bJ6V19o87
"""

# ===============================
# 1. IMPORT LIBRARIES
# ===============================
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

# ===============================
# 2. LOAD DATA
# ===============================
df = pd.read_csv("/content/p2_data.csv")

# Ensure correct columns
df = df[['user', 'topic', 'weight']]
print(df.head())
print(df.columns)

# ===============================
# 3. BUILD ORIGINAL NETWORK
# ===============================
B = nx.Graph()

users = df['user'].unique()
topics = df['topic'].unique()

B.add_nodes_from(users, bipartite=0)
B.add_nodes_from(topics, bipartite=1)

for _, row in df.iterrows():
    B.add_edge(row['user'], row['topic'], weight=row['weight'])

print("Original Network")
print("Nodes:", B.number_of_nodes())
print("Edges:", B.number_of_edges())

# ===============================
# 4. VISUALIZE ORIGINAL NETWORK
# ===============================
plt.figure(figsize=(10,8))

pos = nx.spring_layout(B, k=0.15, seed=42)

nx.draw(B,
        pos,
        node_size=15,
        width=0.2,
        with_labels=False)

plt.title("Original User–Topic Network")
plt.show()

# ===============================
# 5. APPLY ISLAND METHOD
# ===============================
threshold = 5   # strong ties only

# Keep strong edges
df_filtered = df[df['weight'] >= threshold]

# Keep top active users (reduces clutter)
top_users = df.groupby('user')['weight'].sum().nlargest(50).index

df_filtered = df_filtered[df_filtered['user'].isin(top_users)]

# ===============================
# 6. BUILD REDUCED NETWORK
# ===============================
B_filtered = nx.Graph()

users_f = df_filtered['user'].unique()
topics_f = df_filtered['topic'].unique()

B_filtered.add_nodes_from(users_f, bipartite=0)
B_filtered.add_nodes_from(topics_f, bipartite=1)

for _, row in df_filtered.iterrows():
    B_filtered.add_edge(row['user'], row['topic'], weight=row['weight'])

print("\nReduced Network (Island Method)")
print("Nodes:", B_filtered.number_of_nodes())
print("Edges:", B_filtered.number_of_edges())

# ===============================
# 7. VISUALIZE REDUCED NETWORK
# ===============================
plt.figure(figsize=(12,10))

pos2 = nx.spring_layout(B_filtered, k=0.3, seed=42)

# Color nodes by type
color_map = []
for node in B_filtered:
    if node in users_f:
        color_map.append('skyblue')   # Users
    else:
        color_map.append('orange')    # Topics

# Edge thickness based on weight
edge_widths = [B_filtered[u][v]['weight'] * 0.4 for u, v in B_filtered.edges()]

nx.draw(B_filtered,
        pos2,
        node_color=color_map,
        node_size=60,
        width=edge_widths,
        with_labels=False)

plt.title("Reduced Network (Island Method Applied)")
plt.show()

# ===============================
# 8. CENTRALITY
# ===============================
centrality = nx.degree_centrality(B_filtered)

top_nodes = sorted(centrality.items(), key=lambda x: x[1], reverse=True)[:5]

print("\nTop Central Nodes:")
for node, score in top_nodes:
    print(node, round(score, 4))